const translations = {
 
    ru: {
        wbTitle: "Что мы строим",
        wbSubtitle: "Мы специализируемся на SIP-домах и индивидуальном строительстве под заказ.",
        wb1Title: "SIP-дома",
        wb1Desc: "Энергоэффективные дома из готовых SIP-панелей: высокая теплоизоляция, быстрая стройка, под ключ за 3–6 месяцев. Идеально для дотаций KfW 40/55.",
        wb2Title: "Индивидуальное строительство",
        wb2Desc: "Ваш дом по вашим меркам — в том числе в классической массивной технологии. Индивидуальный проект, надёжное качество и оформление полностью по вашим пожеланиям.",
        wbHint: "Не уверены, какая технология подойдёт? Честно проконсультируем бесплатно.",
        kfwB1: "KfW 297/298 — новостройка Effizienzhaus 40/55 (кредит до 150.000 €)",
        kfwB2: "KfW 458 — тепловой насос, дотация 30–70 %",
        kfwB3: "Дотация BAFA на возобновляемую энергию",
        kfwB4: "Энергоэксперт DENA включён (обязателен для KfW)",
        ablaufEyebrow: "Как мы работаем",
        ab1T: "Бесплатная первичная консультация",
        ab1D: "Участок, желаемая площадь, бюджет, сроки — анализируем вашу ситуацию бесплатно.",
        ab2T: "Предложение и проект",
        ab2D: "Готовим детальное предложение с фикс-ценой + план. Координируем энергоэксперта DENA.",
        ab3T: "Подача заявки KfW",
        ab3D: "До начала стройки вместе подаём заявку на дотацию — обязательно для KfW 297/298.",
        ab4T: "Строительство и сдача",
        ab4D: "3–6 месяцев строительства. Еженедельные отчёты. Передача ключей с актом приёмки.",
        ab5T: "5 лет гарантии",
        ab5D: "Письменная гарантия на строение и герметичность. Ваш дом — ваша уверенность.",
        faqEyebrow: "Частые вопросы",
        faqQ1: "Сколько стоит SIP-дом под ключ?",
        faqA1: "Дом под ключ у нас возможен от 150.000 €. Точную цену вы получите после бесплатной консультации — она зависит от участка, размера и оснащения. С дотацией KfW ваша доля затрат дополнительно снижается.",
        faqQ2: "Сколько длится строительство?",
        faqA2: "Коробка SIP-дома монтируется за 2–4 недели. Весь процесс от первого этапа до передачи ключей обычно занимает 3–6 месяцев.",
        faqQ3: "Могу ли я получить дотацию KfW?",
        faqA3: "Да. SIP-дома достигают класса энергоэффективности 40 или 55 и подходят под KfW 297/298 — льготный кредит до 150.000 €. Заявку нужно подать до начала стройки.",
        faqQ4: "Вы строите только в Берлине?",
        faqA4: "Наш основной регион — Берлин и Бранденбург. Проекты в других землях обсуждаем индивидуально — свяжитесь с нами.",
        faqQ5: "Насколько энергоэффективны SIP-дома?",
        faqA5: "SIP-дома регулярно достигают класса A+. Расходы на отопление до 60 % ниже, чем у обычного массивного дома. В сочетании с тепловым насосом здание приближается к стандарту пассивного дома.",
        faqQ6: "Выполняете ли отдельные виды работ?",
        faqA6: "Да, можем взять отдельные работы — например, только монтаж SIP, только крышу или только фасад. Но комплекс «под ключ» экономически выгоднее всего.",
        catPlan: "Планирование",
        catFund: "Фундамент",
        catRoh: "Коробка дома",
        catShell: "Внешняя оболочка",
        catTGA: "Инженерные системы",
        catInner: "Внутренняя отделка",
        srvReq: "Запросить предложение →",
        srvEmpf: "⭐ Рекомендуем",
        fEin: "Один ответственный контакт",
        fFest: "Фиксированная цена — без сюрпризов",
        fZeit: "График работ письменно",
        fGar: "5 лет гарантии на строение",
        fProjekt: "Обсудить проект →",
        b1: "Архитектурный проект + рабочая документация",
        b2: "Статические расчёты",
        b3: "Энергопаспорт (эксперт DENA)",
        b4: "Подготовка заявки на дотацию KfW",
        b5: "Земляные работы и выравнивание",
        b6: "Бетонный фундамент (железобетон)",
        b7: "Дренаж и гидроизоляция",
        b8: "Плита пола с утеплением",
        b9: "SIP Premium Kit (комплект)",
        b10: "Конструкция 4-скатной крыши",
        b11: "Доставка и монтаж краном",
        b12: "Тест на воздухонепроницаемость",
        b13: "Металлическая 4-скатная кровля",
        b14: "16 окон ПВХ (Uw ≤ 0,80)",
        b15: "Входные двери + дверь на террасу",
        b16: "Водостоки и примыкания",
        b17: "Базальтовая вата 100 мм (негорючая)",
        b18: "Армирующая сетка + штукатурка",
        b19: "Силикатная штукатурка по всему фасаду",
        b20: "Гидроизоляция цоколя, примыкания",
        b21: "Тепловой насос (KfW 458 рекомендуется)",
        b22: "Тёплый пол + сантехника",
        b23: "Электрика на 2 квартиры",
        b24: "Вентиляция с рекуперацией тепла",
        b25: "Напольные покрытия (плитка, паркет)",
        b26: "Внутренняя штукатурка, шпаклёвка, покраска",
        b27: "Внутренняя лестница + ~10 межкомнатных дверей",
        b28: "Сантехника + смесители",
        footerPrivacy: "Конфиденциальность",
        footerTagline: "Энергоэффективные SIP-дома под ключ — проектирование и строительство в одних руках.",
        footerNav: "Навигация", footerContact: "Контакты", footerRights: "Все права защищены.",
        priceBlockBadge: "Фиксированная цена под ключ", priceBlockTitle: "SIP-дом под ключ",
        priceBlockDesc: "Полное строительство под ключ — с гарантией фиксированной цены и 5-летней гарантией на дом.",
        priceBlockBtn: "Получить бесплатное предложение",
        lang: "Язык", services: "Услуги", stages: "Этапы строительства",
        stagesDesc: "Полный цикл строительства дома от идеи до заселения",
        advantages: "Преимущества", projects: "Проекты", contacts: "Контакты",
        question: "Есть вопросы?", contact: "Свяжитесь с нами",
        name: "Ваше имя", email: "Ваш email", phone: "Телефон",
        subject: "Тема", message: "Ваше сообщение", send: "Отправить",
        servicesTitle: "Наши услуги", servicesDesc: "Мы предоставляем комплексные услуги в сфере строительства.",
        servicesHeroDesc: "Комплексные решения — от проекта до готового дома под ключ",
        servicesIntro: "Eco Meister Haus предоставляет полный спектр услуг. Мы работаем по технологии SIP и берём на себя весь процесс.",
        service1: "Проектирование", service1Short: "Индивидуальный архитектурный проект под ваш участок и бюджет",
        service2: "Инжиниринг", service2Short: "Электрика, отопление, вентиляция и водоснабжение",
        service3: "Строительство", service3Short: "Возводим дом от фундамента до ключей — быстро, надёжно, по фиксированной цене",
        service1Desc: "Мы создаем современные и эффективные проекты домов.",
        learnMore: "Подробнее", service2Desc: "Комплексные инженерные решения.", service3Desc: "Полный цикл строительства домов.",
        faqTitle: "Частые вопросы",
        faq1Q: "Сколько времени занимает строительство дома?",
        faq1A: "В среднем монтаж коробки занимает 2–4 недели, полный цикл — от 3 до 6 месяцев.",
        faq2Q: "Можно ли изменить проект в процессе строительства?",
        faq2A: "Небольшие изменения возможны до начала производства SIP-панелей.",
        faq3Q: "Даёте ли вы гарантию на построенный дом?",
        faq3A: "Да. Мы предоставляем гарантию на конструктив и все выполненные работы.",
        servicesCtaTitle: "Нужна консультация?", servicesCtaDesc: "Расскажите о вашем проекте — мы ответим на все вопросы",
        contactTitle: "Свяжитесь с нами", contactDetailsTitle: "КОНТАКТНЫЕ ДАННЫЕ",
        formTitle: "Напишите нам", mapTitle: "Где нас найти", mapPlaceholder: "Карта будет добавлена здесь",
        nextStepTitle: "Как мы работаем с вашим запросом",
        step1Title: "Вы пишете или звоните", step1Desc: "Мы ответим в течение 24 часов",
        step2Title: "Мы обсуждаем проект", step2Desc: "Выясняем пожелания, участок и бюджет. Бесплатно.",
        step3Title: "Вы получаете расчёт", step3Desc: "Подготавливаем предварительную смету",
        stagesTitle: "Этапы строительства",
        stage1: "Подготовка участка и фундамент", stage1Desc: "Готовим участок, проводим земляные работы и заливаем надёжный фундамент — основу будущего дома.",
        stage2: "Проектирование и инжиниринг", stage2Desc: "Архитектура, инженерные расчёты и энергоконцепт — с учётом требований KfW и ваших пожеланий.",
        stage3: "Производство SIP панелей", stage3Desc: "SIP-панели изготавливаются точно по проекту на производстве — для максимальной энергоэффективности.",
        stage4: "Доставка и сборка", stage4Desc: "Доставка элементов и быстрая сборка коробки дома — обычно каркас готов за 2–4 недели.",
        stage5: "Кровля и фасад", stage5Desc: "Кровля, окна и фасад делают дом защищённым от погоды и придают ему завершённый вид.",
        stage6: "Инженерные системы", stage6Desc: "Монтаж электрики, отопления, сантехники и вентиляции — все коммуникации прокладываются профессионально.",
        stage7: "Внутренняя отделка", stage7Desc: "Стены, полы, двери и вся отделка — до полностью готового к заселению состояния.",
        stage8: "Проверка и сдача", stage8Desc: "Приёмка всех систем и контроль качества, чтобы всё работало безупречно.",
        stage9: "Сдача и заселение", stage9Desc: "Передача ключей и всех документов — ваш новый дом готов к заселению.",
        ctaStagesTitle: "Готовы начать строительство?", ctaStagesDesc: "Обсудим проект и рассчитаем стоимость",
        ctaContact: "Получить консультацию", ctaProjects: "Смотреть проекты",
        ctaProjectsTitle: "Хотите такой же дом?", ctaProjectsDesc: "Обсудим ваш проект",
        advantagesTitle: "Наши преимущества", advantagesDesc: "Почему клиенты выбирают Eco Meister Haus",
        advIntro: "Eco Meister Haus строит дома по технологии SIP в соответствии с европейскими стандартами.",
        adv1: "Полный цикл строительства", adv1Desc: "От проектирования до сдачи объекта под ключ",
        adv2: "Быстрое строительство", adv2Desc: "Современные технологии сокращают сроки в 2–3 раза",
        adv3: "Экологичные материалы", adv3Desc: "Сертифицированные материалы без вредных выбросов",
        adv4: "Оптимальная стоимость", adv4Desc: "Лучшее соотношение цены и качества",
        adv5: "Современные технологии", adv5Desc: "SIP-панели и инновационные решения",
        adv6: "Индивидуальный подход", adv6Desc: "Учитываем все пожелания клиента",
        adv7: "Энергоэффективность", adv7Desc: "Класс A+ — затраты на отопление ниже до 60%",
        adv8: "Европейские стандарты", adv8Desc: "Строим по европейским нормам",
        advFaqTitle: "Частые вопросы",
        advFaq1Q: "Насколько прочен SIP-дом?", advFaq1A: "SIP-панели выдерживают нагрузки, сопоставимые с кирпичными стенами.",
        advFaq2Q: "Насколько SIP-дом энергоэффективен зимой?", advFaq2A: "Дом класса A+ потребляет на 50–60% меньше энергии на отопление.",
        advFaq3Q: "Соответствует ли строительство европейским нормам?", advFaq3A: "Да. Все панели проходят контроль качества.",
        advCtaTitle: "Убедились в наших преимуществах?", advCtaDesc: "Обсудим ваш проект",
        projectsTitle: "Наши проекты", projectsDesc: "Ознакомьтесь с нашими реализованными проектами домов.",
        catModern: "Современные", catCountry: "Загородные", catMinimal: "Минимализм",
        catModernTitle: "Современные дома", catCountryTitle: "Загородные дома", catMinimalTitle: "Минималистичные дома",
        project1: "Современный дом", project1Desc: "Энергоэффективный дом с современным дизайном.",
        project1Full: "Полностью энергоэффективный дом с использованием SIP-панелей.",
        project2: "Загородный коттедж", project2Desc: "Уютный дом для семьи за городом.",
        project2Full: "Просторный коттедж с террасой и панорамными окнами.",
        project3: "Минималистичный дом", project3Desc: "Стильный дом в современном минимализме.",
        project3Full: "Современный минимализм с функциональной планировкой.",
        viewProject: "Смотреть",
        heroTitle1: "Строим быстрее, проще и эффективнее",
        heroTitle2: "Современные SIP технологии",
        heroTitle3: "Надежные и энергоэффективные дома",
        whyTitle: "Почему Eco Haus Meister", whyDesc: "Четыре причины, по которым нам доверяют строительство своего дома",
        why1Title: "Быстро", why1Desc: "Дом под ключ за 3–6 месяцев благодаря SIP-технологии",
        why2Title: "Экологично", why2Desc: "Только сертифицированные материалы без вредных выбросов",
        why3Title: "По евростандартам", why3Desc: "Строим в соответствии с европейскими нормами",
        why4Title: "Индивидуально", why4Desc: "Каждый проект — под конкретного клиента, участок и бюджет",
        sipBadge: "Технология будущего", sipTitle: "SIP Premium Class — дома нового поколения",
        sipDesc: "SIP-панели — конструкция из двух плит OSB и слоя пенополистирола. Дом держит тепло зимой, прохладу летом и строится в разы быстрее кирпичного.",
        sipPoint1: "Класс энергоэффективности A+ — затраты на отопление до −60%",
        sipPoint2: "Монтаж коробки дома — от 2 до 4 недель",
        sipPoint3: "Срок службы — более 50 лет без потери свойств",
        sipPoint4: "Сертифицировано по европейским стандартам",
        sipCta: "Узнать об этапах строительства",
        sipStat1: "затраты на отопление", sipStat2: "быстрее кирпичного дома",
        sipStat3: "лет срок службы", sipStat4: "класс энергоэффективности",
        materialsTitle: "Материалы и технологии", materialsDesc: "Используем только то, что проверено европейской практикой",
        mat1Title: "OSB + пенополистирол", mat1Desc: "Высококачественный пенополистирол между двумя плитами OSB.",
        mat2Title: "Вентиляция и климат", mat2Desc: "Рекуперация тепла и современные системы климат-контроля.",
        mat3Title: "Фасад и кровля", mat3Desc: "Долговечные фасадные системы и кровля европейских производителей.",
        stagesPreviewTitle: "Как мы строим", stagesPreviewDesc: "От первого звонка до передачи ключей — понятный процесс",
        stagesPrev1: "Участок и фундамент", stagesPrev2: "Проект и панели",
        stagesPrev3: "Сборка и кровля", stagesPrev4: "Отделка и заселение",
        stagesPreviewCta: "Все этапы подробно →",
        projectsPreviewTitle: "Наши проекты", projectsPreviewDesc: "Реализованные дома — от компактных до просторных",
        projectsPreviewCta: "Смотреть все проекты →",
        designBadge: "Только для вас", designTitle: "Индивидуальный дизайн под ваш стиль жизни",
        designDesc: "Каждый дом проектируется под конкретного человека — с учётом участка, семьи, привычек и бюджета.",
        designPoint1: "Свободная планировка", designPoint2: "Выбор фасада и кровли",
        designPoint3: "Любой стиль интерьера", designPoint4: "Под ваш участок и рельеф",
        designCta: "Обсудить проект", ctaBadge: "Начните сегодня",
        ctaMainTitle: "Готовы построить дом своей мечты?",
        ctaMainDesc: "Расскажите нам о вашем проекте — мы рассчитаем стоимость и ответим на все вопросы. Бесплатно.",
        ctaMainBtn1: "Получить консультацию", ctaMainBtn2: "Смотреть проекты",
        aboutTitle: "О нашей компании", aboutDesc: "Мы специализируемся на SIP-домах и индивидуальном строительстве под заказ.",
        about: "О компании", aboutHeroTitle: "О компании",
        aboutHeroDesc: "Строим современные, надёжные и энергоэффективные дома по европейским стандартам",
        aboutCompanyTitle: "Кто мы",
        aboutCompanyText1: "Eco Meister Haus — команда строительных специалистов. Мы строим энергоэффективные SIP-дома и индивидуальные проекты под заказ — всё по европейским стандартам.",
        aboutCompanyText2: "Наша цель — строить дома, в которых комфортно жить и выгодно содержать.",
        aboutValuesTitle: "Наши принципы", aboutValuesDesc: "Качество, экологичность и европейские стандарты — в каждом проекте",
        val1Title: "Экологичность", val1Desc: "Используем только безопасные, сертифицированные материалы",
        val2Title: "Качество", val2Desc: "Каждый этап проходит контроль качества",
        val3Title: "Европейские стандарты", val3Desc: "Строим в соответствии с европейскими нормами",
        aboutApproachTitle: "Наш подход", aboutApproachDesc: "Как мы работаем с каждым клиентом",
        approach1Title: "Слушаем и понимаем", approach1Desc: "Начинаем с детального разговора о ваших пожеланиях.",
        approach2Title: "Проектируем под вас", approach2Desc: "Разрабатываем индивидуальный проект.",
        approach3Title: "Строим прозрачно", approach3Desc: "Регулярные отчёты, фиксированная смета без скрытых доплат.",
        approach4Title: "Сдаём под ключ", approach4Desc: "Передаём готовый дом с полным пакетом документов и гарантией.",
        aboutTechTitle: "Технологии и материалы",
        aboutTechText1: "В основе наших домов — технология SIP. Сэндвич-панели из OSB и пенополистирола.",
        aboutTechText2: "Дом на SIP возводится быстрее кирпичного. Затраты на отопление снижаются до 60%.",
        techStat1: "затраты на отопление", techStat2: "быстрее кирпичного дома",
        techStat3: "лет срок службы", techStat4: "класс энергоэффективности",
        aboutCtaTitle: "Готовы построить дом вашей мечты?", aboutCtaDesc: "Мы подберём оптимальное решение и рассчитаем стоимость",
        bank: "БАНКОВСКИЕ ДАННЫЕ", social: "СОЦИАЛЬНЫЕ СЕТИ",
        srvSectionTitle: "Что мы предлагаем",
        srvSectionDesc: "Все услуги из одних рук — никаких хлопот с координацией",
        srv1Title: "Монтаж SIP и коробка дома",
        srv1Desc: "Поставка и монтаж SIP-комплекта включая кровельную конструкцию. Коробка дома за 2–4 недели.",
        srv2Title: "Фундамент и земляные работы",
        srv2Desc: "Бетонный фундамент по статическим планам, земляные работы, дренаж и плита.",
        srv3Title: "Кровля, окна и двери",
        srv3Desc: "Металлическая кровля, ПВХ-окна (Uw ≤ 0,80), наружные и внутренние двери — полный монтаж.",
        srv4Title: "Фасад и штукатурка",
        srv4Desc: "Система наружного утепления с базальтовой ватой 100 мм + армирующая штукатурка + силикатная штукатурка. Класс A+.",
        srv5Title: "Инженерные системы (TGA)",
        srv5Desc: "Отопление, сантехника и электрика — полная установка по немецким нормам.",
        srv6Title: "Внутренняя отделка и финишинг",
        srv6Desc: "Полы, стены, потолки, сантехника — отделка под ключ по вашим пожеланиям.",
        srv7Title: "Проектирование и разрешение на строительство",
        srv7Desc: "Архитектурное проектирование, статика, энергетический паспорт и разрешение по немецкому строительному праву.",
        srv8Title: "Всё из одних рук — под ключ",
        srv8Desc: "Никаких хлопот с координацией, никакого риска. Мы берём на себя каждый шаг и передаём готовый дом с гарантией.",
        srvCalcTitle: "Пример расчёта: SIP-дом 174 м²",
        srvCalcDesc: "Реальный проект — с разбивкой по видам работ. Ваша цена зависит от участка, комплектации и региона.",
        kfwTitle: "До 150.000 € субсидий на ваш SIP-дом",
        kfwDesc: "Наши дома соответствуют требованиям программ KfW. Мы сопровождаем вас при подаче заявки.",
        kfwProcess: "Как мы работаем",
        srvFaqTitle: "Что спрашивают наши клиенты",
        srvCtaTitle: "Готовы спланировать ваш дом?",
        srvCtaDesc: "Расскажите нам о вашем участке и пожеланиях — мы подготовим бесплатное предложение в течение 48 часов.",
        srvCtaBtn: "Запросить бесплатно",
        srvFaq1Q: "Сколько стоит дом SIP под ключ?",
        srvFaq1A: "От ~260 €/м² за SIP-комплект, или 700–900 €/м² за полностью готовый дом включая фундамент, инженерию и отделку. Наш пример (174 м², Берлин) — около 151.667 € до вычета субсидий KfW.",
        srvFaq2Q: "Сколько длится строительство?",
        srvFaq2A: "Коробка SIP-дома монтируется за 2–4 недели. Весь процесс от первой лопаты до передачи ключей занимает обычно 3–6 месяцев.",
        srvFaq3Q: "Могу ли я получить субсидию KfW?",
        srvFaq3A: "Да. SIP-дома могут достигать класса энергоэффективности 40 или 55 и квалифицироваться по KfW 297/298 — льготный кредит до 150.000 €. Заявку нужно подать до начала строительства.",
        srvFaq4Q: "Вы строите только в Берлине?",
        srvFaq4A: "Основной регион — Берлин и Бранденбург. Проекты в других федеральных землях обсуждаем индивидуально — обращайтесь.",
        srvFaq5Q: "Насколько энергоэффективны SIP-дома?",
        srvFaq5A: "SIP-дома регулярно достигают класса A+. Затраты на отопление на 60% ниже, чем в традиционном доме. В сочетании с тепловым насосом дом приближается к стандарту пассивного дома.",
        srvFaq6Q: "Можно ли заказать отдельные виды работ?",
        srvFaq6A: "Да, мы можем взять отдельные виды работ — например только монтаж SIP, только кровлю или только фасад. Но полный пакет экономически выгоднее.",
        srvCtaLang: "Мы говорим на немецком, английском, русском и румынском языках",
    },
 
    en: {
        wbTitle: "What we build",
        wbSubtitle: "We specialize in SIP houses and individual custom home building.",
        wb1Title: "SIP houses",
        wb1Desc: "Energy-efficient homes from prefabricated SIP panels: highly insulated, quickly built and turnkey in 3–6 months. Ideal for KfW funding 40/55.",
        wb2Title: "Custom home building",
        wb2Desc: "Your home built to measure — including classic solid construction. Individual planning, robust quality and design entirely to your wishes.",
        wbHint: "Not sure which method suits you? We'll advise you honestly and free of charge.",
        kfwB1: "KfW 297/298 — new efficiency house 40/55 (loan up to €150,000)",
        kfwB2: "KfW 458 — heat pump, subsidy 30–70%",
        kfwB3: "BAFA subsidy for renewable energy",
        kfwB4: "DENA energy advisor included (required for KfW)",
        ablaufEyebrow: "Our process",
        ab1T: "Free initial consultation",
        ab1D: "Plot, desired size, budget, timeline — we analyse your situation at no cost.",
        ab2T: "Quote & planning",
        ab2D: "We prepare a detailed fixed-price quote + floor plan and coordinate the DENA advisor.",
        ab3T: "Submit KfW application",
        ab3D: "Before construction we apply for funding together — required for KfW 297/298.",
        ab4T: "Construction & handover",
        ab4D: "3–6 months build time. Weekly progress reports. Handover with acceptance protocol.",
        ab5T: "5-year warranty",
        ab5D: "Written warranty on structure and airtightness. Your home — your security.",
        faqEyebrow: "FAQ",
        faqQ1: "How much does a turnkey SIP house cost?",
        faqA1: "A turnkey SIP house starts at €150,000 with us. You'll get the exact price after a free consultation — depending on plot, size and fit-out. With KfW funding your own contribution drops further.",
        faqQ2: "How long does construction take?",
        faqA2: "The SIP shell is assembled in 2–4 weeks. The whole process from groundbreaking to handover usually takes 3–6 months.",
        faqQ3: "Can I get KfW funding?",
        faqA3: "Yes. SIP houses can reach energy class 40 or 55 and qualify for KfW 297/298 — a low-interest loan up to €150,000. The application must be filed before construction starts.",
        faqQ4: "Do you only build in Berlin?",
        faqA4: "We focus on Berlin and the Brandenburg region. Projects in other states we discuss case by case — get in touch.",
        faqQ5: "How energy-efficient are SIP houses?",
        faqA5: "SIP houses regularly reach energy class A+. Heating costs are up to 60% lower than a conventional solid build. Combined with a heat pump, the building approaches passive-house standard.",
        faqQ6: "Do you also offer individual trades?",
        faqA6: "Yes, we can take on individual services — e.g. only SIP assembly, only roof or only facade. The all-in package is, however, the most cost-effective.",
        catPlan: "Planning",
        catFund: "Foundation",
        catRoh: "Shell construction",
        catShell: "Building envelope",
        catTGA: "Building services",
        catInner: "Interior fit-out",
        srvReq: "Request a quote →",
        srvEmpf: "⭐ Recommended",
        fEin: "One point of contact",
        fFest: "Fixed price — no surprises",
        fZeit: "Written schedule",
        fGar: "5-year structural warranty",
        fProjekt: "Discuss your project →",
        b1: "Architectural design + execution",
        b2: "Structural calculations",
        b3: "Energy certificate (DENA advisor)",
        b4: "KfW funding application prepared",
        b5: "Excavation & levelling",
        b6: "Concrete foundation (reinforced)",
        b7: "Drainage & waterproofing",
        b8: "Insulated floor slab",
        b9: "SIP Premium Kit",
        b10: "4-gable roof structure",
        b11: "Transport & crane assembly",
        b12: "Airtightness test",
        b13: "Metal 4-gable roof",
        b14: "16 PVC windows (Uw ≤ 0.80)",
        b15: "Exterior doors + terrace door",
        b16: "Gutters & connections",
        b17: "Basalt wool 100 mm (non-combustible)",
        b18: "Reinforcement mesh + render",
        b19: "Silicate render on the entire facade",
        b20: "Plinth sealing, connections",
        b21: "Heat pump (KfW 458 recommended)",
        b22: "Underfloor heating + plumbing",
        b23: "Electrical for 2 units",
        b24: "Ventilation with heat recovery",
        b25: "Flooring (tiles, parquet)",
        b26: "Interior plaster, filling, painting",
        b27: "Interior staircase + ~10 interior doors",
        b28: "Sanitary ware + fittings",
        footerPrivacy: "Privacy Policy",
        footerTagline: "Energy-efficient turnkey SIP houses — designed and built from a single source.",
        footerNav: "Navigation", footerContact: "Contact", footerRights: "All rights reserved.",
        priceBlockBadge: "Fixed turnkey price", priceBlockTitle: "Turnkey SIP house",
        priceBlockDesc: "Complete build from a single contractor — with fixed-price guarantee and a 5-year warranty.",
        priceBlockBtn: "Request a free quote",
        lang: "Language", services: "Services", stages: "Construction Stages",
        stagesDesc: "Complete house construction process from idea to move-in",
        advantages: "Advantages", projects: "Projects", contacts: "Contacts",
        question: "Any questions?", contact: "Contact Us",
        name: "Your name", email: "Your email", phone: "Phone",
        subject: "Subject", message: "Your message", send: "Send",
        servicesTitle: "Our Services", servicesDesc: "We provide comprehensive construction services.",
        servicesHeroDesc: "Comprehensive solutions — from design to turnkey home",
        servicesIntro: "Eco Meister Haus provides a full range of energy-efficient home construction services.",
        service1: "Design", service1Short: "Individual architectural project for your plot and budget",
        service2: "Engineering", service2Short: "Electrical, heating, ventilation and water supply",
        service3: "Construction", service3Short: "We build from foundation to keys — fast, reliable, fixed price",
        service1Desc: "We create modern and efficient house designs.",
        learnMore: "Learn more", service2Desc: "Engineering solutions.", service3Desc: "Full construction cycle.",
        faqTitle: "FAQ",
        faq1Q: "How long does it take to build a house?",
        faq1A: "Shell takes 2–4 weeks, full turnkey cycle 3–6 months.",
        faq2Q: "Can the project be changed during construction?",
        faq2A: "Minor changes possible before SIP panel production starts.",
        faq3Q: "Do you provide a warranty?",
        faq3A: "Yes. Warranty on structure and all completed work.",
        servicesCtaTitle: "Need a consultation?", servicesCtaDesc: "Tell us about your project",
        contactTitle: "Contact Us", contactDetailsTitle: "CONTACT DETAILS",
        formTitle: "Write to us", mapTitle: "Where to find us", mapPlaceholder: "Map will be added here",
        nextStepTitle: "How we handle your request",
        step1Title: "You write or call", step1Desc: "We'll respond within 24 hours",
        step2Title: "We discuss the project", step2Desc: "We clarify wishes, plot and budget. Free.",
        step3Title: "You receive an estimate", step3Desc: "We prepare a preliminary budget",
        stagesTitle: "Construction Stages",
        stage1: "Site preparation & foundation", stage1Desc: "We prepare the plot, carry out earthworks and lay a solid foundation as the base of your home.",
        stage2: "Design & engineering", stage2Desc: "Architecture, structural calculations and an energy concept — aligned with KfW requirements and your wishes.",
        stage3: "SIP panel production", stage3Desc: "The custom SIP panels are precisely manufactured in production for maximum energy efficiency.",
        stage4: "Delivery & assembly", stage4Desc: "Delivery of the elements and fast assembly of the building shell — the structure is usually up in just 2–4 weeks.",
        stage5: "Roof & exterior", stage5Desc: "Roofing, windows and facade make the house weatherproof and give it its character.",
        stage6: "Engineering systems", stage6Desc: "Installation of electrics, heating, plumbing and ventilation — all lines professionally routed.",
        stage7: "Interior finishing", stage7Desc: "Walls, floors, doors and the complete fit-out up to a turnkey interior.",
        stage8: "Testing & inspection", stage8Desc: "Inspection of all systems and quality control so everything works flawlessly.",
        stage9: "Handover & move-in", stage9Desc: "Handover of keys and all documents — your new home is ready to move in.",
        ctaStagesTitle: "Ready to start building?", ctaStagesDesc: "Contact us to discuss your project",
        ctaContact: "Get a consultation", ctaProjects: "View projects",
        ctaProjectsTitle: "Want a similar home?", ctaProjectsDesc: "We'll discuss your project",
        advantagesTitle: "Our Advantages", advantagesDesc: "Why clients choose Eco Haus Meister",
        advIntro: "Eco Meister Haus builds energy-efficient homes to European standards.",
        adv1: "Full construction cycle", adv1Desc: "From design to turnkey delivery",
        adv2: "Fast construction", adv2Desc: "Modern technologies reduce timelines",
        adv3: "Eco-friendly materials", adv3Desc: "Safe and energy-efficient solutions",
        adv4: "Optimal pricing", adv4Desc: "Best price-quality ratio",
        adv5: "Modern technologies", adv5Desc: "SIP and innovative solutions",
        adv6: "Individual approach", adv6Desc: "We consider all client needs",
        adv7: "Energy efficiency", adv7Desc: "Class A+ — heating costs reduced up to 60%",
        adv8: "European standards", adv8Desc: "We build to European norms",
        advFaqTitle: "FAQ",
        advFaq1Q: "How durable is a SIP house?", advFaq1A: "SIP panels withstand loads comparable to brick walls.",
        advFaq2Q: "How energy-efficient is a SIP house in winter?", advFaq2A: "A+ class house uses 50–60% less heating energy.",
        advFaq3Q: "Does construction comply with European standards?", advFaq3A: "Yes. All panels undergo quality control.",
        advCtaTitle: "Convinced of our advantages?", advCtaDesc: "Contact us to discuss your project",
        projectsTitle: "Our Projects", projectsDesc: "Explore our completed projects.",
        catModern: "Modern", catCountry: "Country", catMinimal: "Minimalist",
        catModernTitle: "Modern homes", catCountryTitle: "Country homes", catMinimalTitle: "Minimalist homes",
        project1: "Modern House", project1Desc: "Energy-efficient house with modern design.",
        project1Full: "Fully energy-efficient house with SIP panels.",
        project2: "Country Cottage", project2Desc: "Cozy house for a family outside the city.",
        project2Full: "Spacious cottage with terrace and panoramic windows.",
        project3: "Minimalist House", project3Desc: "Stylish house in modern minimalist design.",
        project3Full: "Modern minimalism with functional layout.",
        viewProject: "View",
        heroTitle1: "Build faster, easier and more efficiently",
        heroTitle2: "Modern SIP technologies",
        heroTitle3: "Reliable and energy-efficient homes",
        whyTitle: "Why Eco Haus Meister", whyDesc: "Four reasons people trust us to build their home",
        why1Title: "Fast", why1Desc: "Turnkey home in 3–6 months",
        why2Title: "Eco-friendly", why2Desc: "Certified materials, no harmful emissions",
        why3Title: "European standards", why3Desc: "We build to European energy efficiency norms",
        why4Title: "Individual", why4Desc: "Every project tailored to client, plot and budget",
        sipBadge: "Technology of the future", sipTitle: "SIP Premium Class — next generation homes",
        sipDesc: "SIP panels — two OSB boards with polystyrene foam between them. Warm in winter, cool in summer, built faster than brick.",
        sipPoint1: "Energy class A+ — heating costs up to −60%",
        sipPoint2: "Frame installation — 2 to 4 weeks",
        sipPoint3: "Service life — over 50 years",
        sipPoint4: "Certified to European standards",
        sipCta: "Learn about construction stages",
        sipStat1: "heating cost reduction", sipStat2: "faster than brick",
        sipStat3: "years service life", sipStat4: "energy efficiency class",
        materialsTitle: "Materials and technologies", materialsDesc: "Only proven by European practice",
        mat1Title: "OSB + polystyrene foam", mat1Desc: "High-quality polystyrene foam between two OSB boards.",
        mat2Title: "Ventilation and climate", mat2Desc: "Heat recovery and modern climate control systems.",
        mat3Title: "Facade and roofing", mat3Desc: "Durable facade systems from European manufacturers.",
        stagesPreviewTitle: "How we build", stagesPreviewDesc: "From first call to key handover — clear process",
        stagesPrev1: "Plot and foundation", stagesPrev2: "Design and panels",
        stagesPrev3: "Assembly and roofing", stagesPrev4: "Finishing and move-in",
        stagesPreviewCta: "All stages in detail →",
        projectsPreviewTitle: "Our projects", projectsPreviewDesc: "Completed homes — compact to spacious",
        projectsPreviewCta: "View all projects →",
        designBadge: "Just for you", designTitle: "Individual design for your lifestyle",
        designDesc: "Every home designed for a specific person — plot, family, habits and budget.",
        designPoint1: "Free layout", designPoint2: "Choice of facade and roof",
        designPoint3: "Any interior style", designPoint4: "Tailored to your plot",
        designCta: "Discuss a project", ctaBadge: "Start today",
        ctaMainTitle: "Ready to build your dream home?",
        ctaMainDesc: "Tell us about your project — we'll calculate the cost and answer all questions. Free.",
        ctaMainBtn1: "Get a consultation", ctaMainBtn2: "View projects",
        aboutTitle: "About our company", aboutDesc: "We specialize in SIP houses and individual custom home building.",
        about: "About Us", aboutHeroTitle: "About Us",
        aboutHeroDesc: "Building modern, reliable and energy-efficient homes to European standards",
        aboutCompanyTitle: "Who we are",
        aboutCompanyText1: "Eco Meister Haus is a team of construction specialists. We build energy-efficient SIP houses and individual custom projects — all to European standards.",
        aboutCompanyText2: "Our goal is to build homes that are comfortable to live in and cost-effective to maintain.",
        aboutValuesTitle: "Our principles", aboutValuesDesc: "Quality, ecology and European standards — in every project",
        val1Title: "Eco-friendly", val1Desc: "Only safe, certified materials",
        val2Title: "Quality", val2Desc: "Every stage undergoes quality control",
        val3Title: "European standards", val3Desc: "We build to European regulations",
        aboutApproachTitle: "Our approach", aboutApproachDesc: "How we work with every client",
        approach1Title: "We listen and understand", approach1Desc: "Detailed conversation about your wishes.",
        approach2Title: "We design for you", approach2Desc: "Individual project for your plot and lifestyle.",
        approach3Title: "We build transparently", approach3Desc: "Regular reports, fixed budget, no hidden costs.",
        approach4Title: "We deliver turnkey", approach4Desc: "Complete documents and warranty.",
        aboutTechTitle: "Technologies and materials",
        aboutTechText1: "SIP technology — sandwich panels of OSB and polystyrene foam.",
        aboutTechText2: "SIP house built faster than brick. Heating costs reduced by up to 60%.",
        techStat1: "heating cost savings", techStat2: "faster than brick",
        techStat3: "years service life", techStat4: "energy efficiency class",
        aboutCtaTitle: "Ready to build your dream home?", aboutCtaDesc: "We'll find the optimal solution and calculate the cost",
        bank: "BANK DETAILS", social: "SOCIAL MEDIA",
        srvSectionTitle: "What we offer",
        srvSectionDesc: "All services from one source — no coordination hassle for you",
        srv1Title: "SIP Assembly & Shell",
        srv1Desc: "Delivery and installation of the SIP kit including roof structure. House shell ready in 2–4 weeks.",
        srv2Title: "Foundation & Earthworks",
        srv2Desc: "Concrete foundation according to structural plans, earthworks, drainage and base slab.",
        srv3Title: "Roof, Windows & Doors",
        srv3Desc: "Metal roof, PVC windows (Uw ≤ 0.80), exterior and interior doors — fully installed.",
        srv4Title: "ETICS Facade & Plaster",
        srv4Desc: "External thermal insulation system with basalt wool 100mm + reinforcing plaster + silicate plaster. Energy class A+.",
        srv5Title: "Building Services (TGA)",
        srv5Desc: "Heating, plumbing and electrical — complete installation to German standards.",
        srv6Title: "Interior Finishing",
        srv6Desc: "Floors, walls, ceilings, sanitary ware — turnkey interior finishing to your wishes.",
        srv7Title: "Planning & Building Permit",
        srv7Desc: "Architectural planning, statics, energy certificate and building permit under German construction law.",
        srv8Title: "Everything from one source — turnkey",
        srv8Desc: "No coordination hassle, no risk. We handle every step and hand over a move-in-ready house with warranty.",
        srvCalcTitle: "Sample Calculation: SIP House 174 m²",
        srvCalcDesc: "A real project — broken down by trade. Your price depends on plot, specification and region.",
        kfwTitle: "Up to €150,000 Funding for Your SIP House",
        kfwDesc: "Our houses meet the requirements for KfW funding programmes. We support you with the application.",
        kfwProcess: "How we proceed",
        srvFaqTitle: "What our clients ask",
        srvCtaTitle: "Ready to plan your house?",
        srvCtaDesc: "Tell us about your plot and wishes — we will provide a free quote within 48 hours.",
        srvCtaBtn: "Request for free",
        srvFaq1Q: "How much does a turnkey SIP house cost?",
        srvFaq1A: "From ~260 €/m² for the SIP kit alone, or 700–900 €/m² for a fully turnkey house including foundation, MEP and interior finishing. Our sample project (174 m², Berlin) is approximately 151,667 € before KfW deductions.",
        srvFaq2Q: "How long does construction take?",
        srvFaq2A: "The SIP house shell is assembled in 2–4 weeks. The entire process from groundbreaking to key handover typically takes 3–6 months.",
        srvFaq3Q: "Can I get KfW funding?",
        srvFaq3A: "Yes. SIP houses can achieve energy efficiency class 40 or 55 and qualify for KfW 297/298 — a low-interest loan of up to 150,000 €. The application must be submitted before construction begins.",
        srvFaq4Q: "Do you only build in Berlin?",
        srvFaq4A: "Our main region is Berlin and Brandenburg. Projects in other federal states are discussed on a case-by-case basis — contact us.",
        srvFaq5Q: "How energy-efficient are SIP houses?",
        srvFaq5A: "SIP houses regularly achieve energy class A+. Heating costs are up to 60% lower than in a conventional building. Combined with a heat pump, the building approaches passive house standard.",
        srvFaq6Q: "Can I order individual trades only?",
        srvFaq6A: "Yes, we can take on individual services — e.g. SIP assembly only, roofing only or facade only. However, the full package is economically most advantageous.",
        srvCtaLang: "We speak German, English, Russian & Romanian.",
    },
 
    ro: {
        wbTitle: "Ce construim",
        wbSubtitle: "Ne specializăm în case SIP și construcții individuale la comandă.",
        wb1Title: "Case SIP",
        wb1Desc: "Case eficiente energetic din panouri SIP prefabricate: izolație ridicată, construcție rapidă, la cheie în 3–6 luni. Ideal pentru finanțarea KfW 40/55.",
        wb2Title: "Construcție individuală",
        wb2Desc: "Casa dvs. după măsură — inclusiv în construcție masivă clasică. Proiectare individuală, calitate robustă și design complet după dorințele dvs.",
        wbHint: "Nu sunteți sigur ce sistem vi se potrivește? Vă consiliem cinstit și gratuit.",
        kfwB1: "KfW 297/298 — casă eficientă nouă 40/55 (credit până la 150.000 €)",
        kfwB2: "KfW 458 — pompă de căldură, subvenție 30–70 %",
        kfwB3: "Subvenție BAFA pentru energie regenerabilă",
        kfwB4: "Expert energetic DENA inclus (obligatoriu pentru KfW)",
        ablaufEyebrow: "Cum lucrăm",
        ab1T: "Prima consultație gratuită",
        ab1D: "Teren, suprafață dorită, buget, termene — analizăm situația dvs. gratuit.",
        ab2T: "Ofertă și planificare",
        ab2D: "Pregătim o ofertă detaliată cu preț fix + plan. Coordonăm expertul energetic DENA.",
        ab3T: "Depunerea cererii KfW",
        ab3D: "Înainte de începerea lucrărilor depunem împreună cererea — obligatoriu pentru KfW 297/298.",
        ab4T: "Construcție și predare",
        ab4D: "3–6 luni de construcție. Rapoarte săptămânale. Predarea cheilor cu proces-verbal.",
        ab5T: "5 ani garanție",
        ab5D: "Garanție scrisă pentru structură și etanșeitate. Casa dvs. — siguranța dvs.",
        faqEyebrow: "Întrebări frecvente",
        faqQ1: "Cât costă o casă SIP la cheie?",
        faqA1: "O casă SIP la cheie este posibilă la noi de la 150.000 €. Prețul exact îl primiți după o consultație gratuită — în funcție de teren, dimensiune și dotări. Cu finanțarea KfW, contribuția proprie scade suplimentar.",
        faqQ2: "Cât durează construcția?",
        faqA2: "Structura casei SIP se montează în 2–4 săptămâni. Întregul proces, de la început până la predarea cheilor, durează de regulă 3–6 luni.",
        faqQ3: "Pot obține finanțare KfW?",
        faqA3: "Da. Casele SIP pot atinge clasa de eficiență 40 sau 55 și se califică pentru KfW 297/298 — credit cu dobândă redusă până la 150.000 €. Cererea trebuie depusă înainte de începerea lucrărilor.",
        faqQ4: "Construiți doar în Berlin?",
        faqA4: "Ne concentrăm pe Berlin și regiunea Brandenburg. Proiectele din alte landuri le discutăm individual — contactați-ne.",
        faqQ5: "Cât de eficiente energetic sunt casele SIP?",
        faqA5: "Casele SIP ating în mod regulat clasa A+. Costurile de încălzire sunt cu până la 60 % mai mici decât la o construcție masivă convențională. În combinație cu pompa de căldură, clădirea se apropie de standardul casei pasive.",
        faqQ6: "Oferiți și lucrări individuale?",
        faqA6: "Da, putem prelua și lucrări individuale — de ex. doar montaj SIP, doar acoperiș sau doar fațadă. Însă pachetul complet este cel mai avantajos economic.",
        catPlan: "Planificare",
        catFund: "Fundație",
        catRoh: "Structură",
        catShell: "Anvelopă",
        catTGA: "Instalații",
        catInner: "Finisaje interioare",
        srvReq: "Solicitați o ofertă →",
        srvEmpf: "⭐ Recomandat",
        fEin: "Un singur interlocutor",
        fFest: "Preț fix — fără surprize",
        fZeit: "Grafic în scris",
        fGar: "5 ani garanție la structură",
        fProjekt: "Discutați proiectul →",
        b1: "Proiect arhitectural + execuție",
        b2: "Calcul structural",
        b3: "Certificat energetic (expert DENA)",
        b4: "Pregătirea cererii de finanțare KfW",
        b5: "Excavare și nivelare",
        b6: "Fundație din beton (beton armat)",
        b7: "Drenaj și hidroizolație",
        b8: "Placă de fundație cu izolație",
        b9: "Kit SIP Premium",
        b10: "Structură acoperiș în 4 ape",
        b11: "Transport și montaj cu macara",
        b12: "Test de etanșeitate la aer",
        b13: "Acoperiș metalic în 4 ape",
        b14: "16 ferestre PVC (Uw ≤ 0,80)",
        b15: "Uși exterioare + ușă terasă",
        b16: "Jgheaburi și racorduri",
        b17: "Vată bazaltică 100 mm (neinflamabilă)",
        b18: "Plasă de armare + tencuială",
        b19: "Tencuială silicatică pe toată fațada",
        b20: "Hidroizolație soclu, racorduri",
        b21: "Pompă de căldură (KfW 458 recomandat)",
        b22: "Încălzire în pardoseală + sanitare",
        b23: "Instalație electrică 2 apart.",
        b24: "Ventilație cu recuperare de căldură",
        b25: "Pardoseli (gresie, parchet)",
        b26: "Tencuieli interioare, gletuire, vopsire",
        b27: "Scară interioară + ~10 uși interioare",
        b28: "Obiecte sanitare + baterii",
        footerPrivacy: "Confidențialitate",
        footerTagline: "Case SIP eficiente energetic la cheie — proiectare și construcție dintr-o singură sursă.",
        footerNav: "Navigare", footerContact: "Contact", footerRights: "Toate drepturile rezervate.",
        priceBlockBadge: "Preț fix la cheie", priceBlockTitle: "Casă SIP la cheie",
        priceBlockDesc: "Construcție completă la cheie — cu garanție de preț fix și 5 ani garanție.",
        priceBlockBtn: "Solicitați o ofertă gratuită",
        lang: "Limbă", services: "Servicii", stages: "Etapele construcției",
        stagesDesc: "Proces complet de construcție de la idee până la mutare",
        advantages: "Avantaje", projects: "Proiecte", contacts: "Contacte",
        question: "Aveți întrebări?", contact: "Contactați-ne",
        name: "Numele dvs.", email: "Emailul dvs.", phone: "Telefon",
        subject: "Subiect", message: "Mesajul dvs.", send: "Trimite",
        servicesTitle: "Serviciile noastre", servicesDesc: "Oferim servicii complete în domeniul construcțiilor.",
        service1: "Proiectare", service2: "Inginerie", service3: "Construcție",
        service1Desc: "Creăm proiecte moderne și eficiente.",
        learnMore: "Detalii", service2Desc: "Soluții inginerești complete.", service3Desc: "Ciclu complet de construcție.",
        stagesTitle: "Etapele construcției",
        stage1: "Pregătirea terenului și fundația", stage1Desc: "Pregătim terenul, executăm lucrările de excavare și turnăm o fundație solidă — baza casei dumneavoastră.",
        stage2: "Proiectare și inginerie", stage2Desc: "Arhitectură, calcule structurale și concept energetic — conform cerințelor KfW și dorințelor dumneavoastră.",
        stage3: "Producția panourilor SIP", stage3Desc: "Panourile SIP sunt fabricate cu precizie în producție, pentru o eficiență energetică maximă.",
        stage4: "Livrare și montaj", stage4Desc: "Livrarea elementelor și asamblarea rapidă a anvelopei — structura este gata de obicei în doar 2–4 săptămâni.",
        stage5: "Acoperiș și exterior", stage5Desc: "Acoperișul, ferestrele și fațada fac casa rezistentă la intemperii și îi dau aspectul final.",
        stage6: "Sisteme inginerești", stage6Desc: "Montarea instalațiilor electrice, de încălzire, sanitare și de ventilație — toate executate profesional.",
        stage7: "Finisaje interioare", stage7Desc: "Pereți, podele, uși și dotarea completă, până la un interior la cheie.",
        stage8: "Testare și inspecție", stage8Desc: "Verificarea tuturor sistemelor și controlul calității, pentru ca totul să funcționeze impecabil.",
        stage9: "Predare și mutare", stage9Desc: "Predarea cheilor și a tuturor documentelor — noua dumneavoastră casă este gata de locuit.",
        ctaStagesTitle: "Gata să construiți?", ctaStagesDesc: "Contactați-ne pentru discuții",
        ctaContact: "Obțineți consultație", ctaProjects: "Vedeți proiectele",
        ctaProjectsTitle: "Doriți o casă similară?", ctaProjectsDesc: "Vom discuta proiectul dvs.",
        advantagesTitle: "Avantajele noastre", advantagesDesc: "De ce clienții aleg Eco Haus Meister",
        adv1: "Ciclu complet", adv1Desc: "De la proiectare până la predare",
        adv2: "Construcție rapidă", adv2Desc: "Tehnologiile moderne reduc timpul",
        adv3: "Materiale ecologice", adv3Desc: "Materiale certificate",
        adv4: "Cost optim", adv4Desc: "Cel mai bun raport calitate-preț",
        adv5: "Tehnologii moderne", adv5Desc: "SIP și soluții inovatoare",
        adv6: "Abordare individuală", adv6Desc: "Ținem cont de toate cerințele",
        projectsTitle: "Proiectele noastre", projectsDesc: "Descoperiți proiectele noastre.",
        catModern: "Moderne", catCountry: "La țară", catMinimal: "Minimalism",
        catModernTitle: "Case moderne", catCountryTitle: "Case de țară", catMinimalTitle: "Case minimaliste",
        project1: "Casă modernă", project1Desc: "Casă eficientă energetic cu design modern.",
        project1Full: "Casă eficientă energetic cu panouri SIP.",
        project2: "Cabană de țară", project2Desc: "Casă confortabilă în afara orașului.",
        project2Full: "Cabană spațioasă cu terasă și ferestre panoramice.",
        project3: "Casă minimalistă", project3Desc: "Casă elegantă în stil minimalist.",
        project3Full: "Minimalism modern cu planificare funcțională.",
        viewProject: "Vezi",
        heroTitle1: "Construim mai rapid, mai ușor și mai eficient",
        heroTitle2: "Tehnologii SIP moderne",
        heroTitle3: "Case fiabile și eficiente energetic",
        whyTitle: "De ce Eco Haus Meister", whyDesc: "Patru motive pentru care ne încredințează construcția",
        why1Title: "Rapid", why1Desc: "Casă la cheie în 3–6 luni",
        why2Title: "Ecologic", why2Desc: "Materiale certificate fără emisii nocive",
        why3Title: "Standarde europene", why3Desc: "Construim conform normelor europene",
        why4Title: "Individual", why4Desc: "Fiecare proiect — pentru clientul specific",
        sipBadge: "Tehnologia viitorului", sipTitle: "SIP Premium Class — case de nouă generație",
        sipDesc: "Panouri SIP din două plăci OSB cu polistiren între ele. Caldă iarna, răcoroasă vara.",
        sipPoint1: "Clasa A+ — costuri de încălzire reduse cu 60%",
        sipPoint2: "Montaj — 2 până la 4 săptămâni",
        sipPoint3: "Durată — peste 50 de ani",
        sipPoint4: "Certificat conform standardelor europene",
        sipCta: "Aflați despre etape",
        sipStat1: "reducere costuri încălzire", sipStat2: "mai rapid decât cărămida",
        sipStat3: "ani durată", sipStat4: "clasă eficiență energetică",
        materialsTitle: "Materiale și tehnologii", materialsDesc: "Doar materiale dovedite european",
        mat1Title: "OSB + polistiren", mat1Desc: "Polistiren de înaltă calitate între plăci OSB.",
        mat2Title: "Ventilație și climă", mat2Desc: "Recuperare de căldură și sisteme moderne.",
        mat3Title: "Fațadă și acoperiș", mat3Desc: "Sisteme durabile de la producători europeni.",
        stagesPreviewTitle: "Cum construim", stagesPreviewDesc: "De la primul apel până la chei",
        stagesPrev1: "Teren și fundație", stagesPrev2: "Proiect și panouri",
        stagesPrev3: "Asamblare și acoperiș", stagesPrev4: "Finisaje și mutare",
        stagesPreviewCta: "Toate etapele →",
        projectsPreviewTitle: "Proiectele noastre", projectsPreviewDesc: "Case realizate",
        projectsPreviewCta: "Vezi toate proiectele →",
        designBadge: "Doar pentru dvs.", designTitle: "Design individual pentru stilul dvs.",
        designDesc: "Fiecare casă proiectată individual — teren, familie, buget.",
        designPoint1: "Plan liber", designPoint2: "Alegerea fațadei",
        designPoint3: "Orice stil interior", designPoint4: "Adaptat terenului dvs.",
        designCta: "Discutați proiectul", ctaBadge: "Începeți astăzi",
        ctaMainTitle: "Gata să construiți casa visurilor?",
        ctaMainDesc: "Spuneți-ne despre proiect — vom calcula costul. Gratuit.",
        ctaMainBtn1: "Obțineți consultație", ctaMainBtn2: "Vedeți proiectele",
        aboutTitle: "Despre compania noastră", aboutDesc: "Ne specializăm în case SIP și construcții individuale la comandă.",
        about: "Despre noi", aboutHeroTitle: "Despre noi",
        aboutHeroDesc: "Construim case moderne și eficiente energetic conform standardelor europene",
        aboutCompanyTitle: "Cine suntem",
        aboutCompanyText1: "Eco Meister Haus este o echipă de specialiști în construcții. Construim case SIP eficiente energetic și proiecte individuale la comandă — totul conform standardelor europene.",
        aboutCompanyText2: "Scopul nostru — case confortabile și rentabile.",
        aboutValuesTitle: "Principiile noastre", aboutValuesDesc: "Calitate, ecologie și standarde europene",
        val1Title: "Ecologic", val1Desc: "Materiale sigure și certificate",
        val2Title: "Calitate", val2Desc: "Control de calitate la fiecare etapă",
        val3Title: "Standarde europene", val3Desc: "Conform normelor europene",
        aboutApproachTitle: "Abordarea noastră", aboutApproachDesc: "Cum lucrăm cu fiecare client",
        approach1Title: "Ascultăm", approach1Desc: "Conversație detaliată despre dorințele dvs.",
        approach2Title: "Proiectăm", approach2Desc: "Proiect individual adaptat.",
        approach3Title: "Construim transparent", approach3Desc: "Deviz fix fără costuri ascunse.",
        approach4Title: "Predăm la cheie", approach4Desc: "Documente complete și garanție.",
        aboutTechTitle: "Tehnologii și materiale",
        aboutTechText1: "SIP — panouri sandwich din OSB și polistiren.",
        aboutTechText2: "Casă SIP mai rapidă decât cărămida. Costuri încălzire reduse cu 60%.",
        techStat1: "economii încălzire", techStat2: "mai rapid decât cărămida",
        techStat3: "ani durată", techStat4: "clasă eficiență",
        aboutCtaTitle: "Gata să construiți?", aboutCtaDesc: "Vom găsi soluția optimă",
        bank: "DATE BANCARE", social: "REȚELE SOCIALE",
        srvSectionTitle: "Ce oferim",
        srvSectionDesc: "Toate serviciile dintr-un singur loc — fără bătăi de cap cu coordonarea",
        srv1Title: "Montaj SIP & Structură",
        srv1Desc: "Livrare și montaj al kitului SIP inclusiv structura acoperișului. Casa gata în 2–4 săptămâni.",
        srv2Title: "Fundație & Lucrări de Terasament",
        srv2Desc: "Fundație din beton conform planurilor statice, lucrări de terasament, drenaj și placă.",
        srv3Title: "Acoperiș, Ferestre & Uși",
        srv3Desc: "Acoperiș metalic, ferestre PVC (Uw ≤ 0,80), uși exterioare și interioare — montaj complet.",
        srv4Title: "Fațadă ETICS & Tencuială",
        srv4Desc: "Sistem de termoizolație exterioară cu vată bazaltică 100 mm + tencuială armată + tencuială silicatică. Clasa A+.",
        srv5Title: "Instalații (TGA)",
        srv5Desc: "Încălzire, instalații sanitare și electrice — montaj complet conform normelor germane.",
        srv6Title: "Amenajări Interioare",
        srv6Desc: "Podele, pereți, tavane, obiecte sanitare — amenajare la cheie conform dorințelor dvs.",
        srv7Title: "Proiectare & Autorizație de Construcție",
        srv7Desc: "Proiectare arhitecturală, calcule statice, certificat energetic și autorizație conform dreptului german.",
        srv8Title: "Tot dintr-un singur loc — la cheie",
        srv8Desc: "Fără bătăi de cap cu coordonarea, fără riscuri. Preluăm fiecare pas și predăm o casă gata de locuit cu garanție.",
        srvCalcTitle: "Exemplu de Calcul: Casă SIP 174 m²",
        srvCalcDesc: "Un proiect real — detaliat pe meserii. Prețul dvs. depinde de teren, dotări și regiune.",
        kfwTitle: "Până la 150.000 € Finanțare pentru Casa dvs. SIP",
        kfwDesc: "Casele noastre îndeplinesc cerințele programelor de finanțare KfW. Vă însoțim la depunerea cererii.",
        kfwProcess: "Cum procedăm",
        srvFaqTitle: "Ce întreabă clienții noștri",
        srvCtaTitle: "Gata să planificați casa?",
        srvCtaDesc: "Spuneți-ne despre terenul și dorințele dvs. — vom pregăti o ofertă gratuită în 48 de ore.",
        srvCtaBtn: "Solicitați gratuit",
        srvFaq1Q: "Cât costă o casă SIP la cheie?",
        srvFaq1A: "De la ~260 €/m² pentru kitul SIP singur, sau 700–900 €/m² pentru o casă complet la cheie inclusiv fundație, instalații și finisaje. Proiectul nostru exemplu (174 m², Berlin) este de aproximativ 151.667 € înainte de deducerile KfW.",
        srvFaq2Q: "Cât durează construcția?",
        srvFaq2A: "Structura casei SIP se asamblează în 2–4 săptămâni. Întregul proces de la prima lopată până la predarea cheilor durează de obicei 3–6 luni.",
        srvFaq3Q: "Pot obține finanțare KfW?",
        srvFaq3A: "Da. Casele SIP pot atinge clasa de eficiență energetică 40 sau 55 și se pot califica pentru KfW 297/298 — împrumut cu dobândă redusă până la 150.000 €. Cererea trebuie depusă înainte de începerea construcției.",
        srvFaq4Q: "Construiți doar în Berlin?",
        srvFaq4A: "Regiunea noastră principală este Berlin și Brandenburg. Proiectele din alte landuri federale le discutăm de la caz la caz — contactați-ne.",
        srvFaq5Q: "Cât de eficiente energetic sunt casele SIP?",
        srvFaq5A: "Casele SIP ating în mod regulat clasa A+. Costurile de încălzire sunt cu până la 60% mai mici decât în construcțiile convenționale. Combinate cu o pompă de căldură, clădirea se apropie de standardul casei pasive.",
        srvFaq6Q: "Pot comanda doar anumite lucrări?",
        srvFaq6A: "Da, putem prelua servicii individuale — de ex. doar montaj SIP, doar acoperiș sau doar fațadă. Pachetul complet este însă cel mai avantajos economic.",
        srvCtaLang: "Vorbim germană, engleză, rusă și română."
    },
 
    de: {
        wbTitle: "Was wir bauen",
        wbSubtitle: "Wir spezialisieren uns auf SIP-Häuser und individuellen Hausbau nach Maß.",
        wb1Title: "SIP-Häuser",
        wb1Desc: "Energieeffiziente Häuser aus vorgefertigten SIP-Paneelen: hochgedämmt, schnell gebaut und schlüsselfertig in 3–6 Monaten. Ideal für KfW-Förderung 40/55.",
        wb2Title: "Individueller Hausbau",
        wb2Desc: "Ihr Zuhause nach Maß — auch in klassischer Massivbauweise. Individuelle Planung, robuste Qualität und Gestaltung ganz nach Ihren Wünschen.",
        wbHint: "Nicht sicher, welche Bauweise passt? Wir beraten Sie ehrlich und kostenlos.",
        kfwB1: "KfW 297/298 — Neubau Effizienzhaus 40/55 (Kredit bis 150.000 €)",
        kfwB2: "KfW 458 — Wärmepumpe, Zuschuss 30–70 %",
        kfwB3: "BAFA-Zuschuss für erneuerbare Energien",
        kfwB4: "DENA-Energieberater inklusive (Pflicht für KfW)",
        ablaufEyebrow: "Unser Ablauf",
        ab1T: "Kostenloses Erstgespräch",
        ab1D: "Grundstück, Wunschgröße, Budget, Zeitplan — wir analysieren Ihre Situation ohne Kosten.",
        ab2T: "Angebot & Planung",
        ab2D: "Wir erstellen ein detailliertes Festpreisangebot + Grundriss. DENA-Energieberater koordinieren wir.",
        ab3T: "KfW-Antrag stellen",
        ab3D: "Vor Baubeginn beantragen wir gemeinsam die Förderung — Pflichtschritt für KfW 297/298.",
        ab4T: "Bau & Übergabe",
        ab4D: "3–6 Monate Bauzeit. Wöchentliche Fortschrittsberichte. Schlüsselübergabe mit Abnahmeprotokoll.",
        ab5T: "5 Jahre Garantie",
        ab5D: "Schriftliche Gewährleistung auf Bauwerk und Dichtheit. Ihr Haus — Ihre Sicherheit.",
        faqEyebrow: "Häufige Fragen",
        faqQ1: "Was kostet ein SIP-Haus schlüsselfertig?",
        faqA1: "Ein schlüsselfertiges SIP-Haus ist bei uns ab 150.000 € möglich. Den genauen Preis erhalten Sie nach einem kostenlosen Beratungsgespräch — abhängig von Grundstück, Größe und Ausstattung. Mit KfW-Förderung sinkt Ihr Eigenanteil zusätzlich.",
        faqQ2: "Wie lange dauert der Bau?",
        faqA2: "Die SIP-Hausbox (Rohbau) wird in 2–4 Wochen montiert. Der gesamte Prozess vom ersten Spatenstich bis zur Schlüsselübergabe dauert in der Regel 3–6 Monate.",
        faqQ3: "Kann ich KfW-Förderung bekommen?",
        faqA3: "Ja. SIP-Häuser können die Energieeffizienzklasse 40 oder 55 erreichen und damit für KfW 297/298 qualifizieren — zinsgünstiges Darlehen bis 150.000 €. Der Antrag muss vor Baubeginn gestellt werden.",
        faqQ4: "Bauen Sie nur in Berlin?",
        faqA4: "Unser Schwerpunkt liegt in Berlin und der Region Brandenburg. Projekte in anderen Bundesländern besprechen wir gerne im Einzelfall — sprechen Sie uns an.",
        faqQ5: "Wie energieeffizient sind SIP-Häuser?",
        faqA5: "SIP-Häuser erreichen regelmäßig Energieeffizienzklasse A+. Die Heizkosten liegen um bis zu 60 % niedriger als bei einem konventionellen Massivbau. In Kombination mit Wärmepumpe nähert sich das Gebäude dem Passivhausstandard.",
        faqQ6: "Bieten Sie auch einzelne Gewerke an?",
        faqA6: "Ja, wir können auch einzelne Leistungen übernehmen — z. B. nur SIP-Montage, nur Dach oder nur Fassade. Das Rundum-Paket ist jedoch wirtschaftlich am vorteilhaftesten.",
        catPlan: "Planung",
        catFund: "Fundament",
        catRoh: "Rohbau",
        catShell: "Außenhülle",
        catTGA: "Haustechnik",
        catInner: "Innenausbau",
        srvReq: "Angebot anfragen →",
        srvEmpf: "⭐ Empfehlung",
        fEin: "Ein Ansprechpartner",
        fFest: "Festpreis — keine Überraschungen",
        fZeit: "Zeitplan schriftlich",
        fGar: "5 Jahre Garantie auf Bauwerk",
        fProjekt: "Projekt besprechen →",
        b1: "Architekturentwurf + Ausführung",
        b2: "Statische Berechnung",
        b3: "Energieausweis (DENA-Berater)",
        b4: "KfW-Förderantrag vorbereiten",
        b5: "Aushub & Nivellierung",
        b6: "Betonfundament (Stahlbeton)",
        b7: "Drainage & Abdichtung",
        b8: "Bodenplatte mit Dämmung",
        b9: "SIP Premium Kit",
        b10: "4-Giebeldach Konstruktion",
        b11: "Transport & Kranmontage",
        b12: "Luftdichtigkeitstest",
        b13: "Blechdach 4-Giebel",
        b14: "16 Fenster PVC (Uw ≤ 0,80)",
        b15: "Außentüren + Terrassentür",
        b16: "Dachrinnen & Anschlüsse",
        b17: "Basaltwolle 100 mm (nicht brennbar)",
        b18: "Armierungsgewebe + Putz",
        b19: "Silikatputz auf der gesamten Fassade",
        b20: "Sockelabdichtung, Anschlüsse",
        b21: "Wärmepumpe (KfW 458 empfohlen)",
        b22: "Fußbodenheizung + Sanitär",
        b23: "Elektroinstallation 2 Whg.",
        b24: "Lüftung mit Wärmerückgewinnung",
        b25: "Bodenbeläge (Fliesen, Parkett)",
        b26: "Innenputz, Spachtelung, Maler",
        b27: "Innentreppe + ~10 Innentüren",
        b28: "Sanitärkeramik + Armaturen",
        footerPrivacy: "Datenschutz",
        footerTagline: "Energieeffiziente SIP-Häuser schlüsselfertig — geplant und gebaut aus einer Hand.",
        footerNav: "Navigation", footerContact: "Kontakt", footerRights: "Alle Rechte vorbehalten.",
        priceBlockBadge: "Festpreis schlüsselfertig", priceBlockTitle: "SIP-Haus schlüsselfertig",
        priceBlockDesc: "Kompletter Bau aus einer Hand — mit Festpreisgarantie und 5 Jahren Gewährleistung.",
        priceBlockBtn: "Kostenloses Angebot anfragen",
        lang: "Sprache", services: "Dienstleistungen", stages: "Bauphasen",
        stagesDesc: "Kompletter Bauprozess vom Konzept bis zum Einzug",
        advantages: "Vorteile", projects: "Projekte", contacts: "Kontakte",
        question: "Haben Sie Fragen?", contact: "Kontaktieren Sie uns",
        name: "Ihr Name", email: "Ihre E-Mail", phone: "Telefon",
        subject: "Betreff", message: "Ihre Nachricht", send: "Senden",
        servicesTitle: "Unsere Dienstleistungen", servicesDesc: "Wir bieten umfassende Bauleistungen an.",
        servicesHeroDesc: "Umfassende Lösungen — vom Projekt bis zum schlüsselfertigen Haus",
        servicesIntro: "Eco Meister Haus bietet ein vollständiges Spektrum an energieeffizienten Hausbaudienstleistungen.",
        service1: "Planung", service1Short: "Individuelles Architekturprojekt für Ihr Grundstück und Budget",
        service2: "Ingenieurwesen", service2Short: "Elektrik, Heizung, Lüftung und Wasserversorgung",
        service3: "Bau", service3Short: "Wir bauen vom Fundament bis zu den Schlüsseln — schnell, zuverlässig, Festpreis",
        service1Desc: "Wir erstellen moderne und effiziente Hausprojekte.",
        learnMore: "Mehr erfahren", service2Desc: "Ingenieurlösungen.", service3Desc: "Vollständiger Bauzyklus.",
        faqTitle: "Häufige Fragen",
        faq1Q: "Wie lange dauert der Hausbau?",
        faq1A: "Rohbau 2–4 Wochen, vollständiger Zyklus 3–6 Monate.",
        faq2Q: "Kann das Projekt geändert werden?",
        faq2A: "Kleine Änderungen möglich vor dem Produktionsstart.",
        faq3Q: "Geben Sie Garantie auf das Haus?",
        faq3A: "Ja. Garantie auf Konstruktion und alle Arbeiten.",
        servicesCtaTitle: "Brauchen Sie eine Beratung?", servicesCtaDesc: "Erzählen Sie uns von Ihrem Projekt",
        contactTitle: "Kontaktieren Sie uns", contactDetailsTitle: "KONTAKTDATEN",
        formTitle: "Schreiben Sie uns", mapTitle: "Wo Sie uns finden", mapPlaceholder: "Karte wird hier eingefügt",
        nextStepTitle: "Wie wir mit Ihrer Anfrage arbeiten",
        step1Title: "Sie schreiben oder rufen an", step1Desc: "Wir antworten innerhalb von 24 Stunden",
        step2Title: "Wir besprechen das Projekt", step2Desc: "Wir klären Wünsche und Budget. Kostenlos.",
        step3Title: "Sie erhalten eine Kalkulation", step3Desc: "Wir erstellen einen Kostenvoranschlag",
        stagesTitle: "Bauphasen",
        stage1: "Grundstücksvorbereitung & Fundament", stage1Desc: "Wir bereiten das Grundstück vor, führen Erdarbeiten durch und erstellen ein tragfähiges Fundament als Basis für Ihr Haus.",
        stage2: "Planung & Ingenieurwesen", stage2Desc: "Architektur, statische Berechnungen und Energiekonzept — abgestimmt auf KfW-Anforderungen und Ihre Wünsche.",
        stage3: "SIP-Paneele Produktion", stage3Desc: "Die maßgefertigten SIP-Paneele werden präzise in der Produktion gefertigt — für maximale Energieeffizienz.",
        stage4: "Lieferung & Montage", stage4Desc: "Anlieferung der Elemente und schneller Aufbau der Gebäudehülle — der Rohbau steht meist in nur 2–4 Wochen.",
        stage5: "Dach & Außenarbeiten", stage5Desc: "Dacheindeckung, Fenster und Fassade machen das Haus wetterfest und verleihen ihm sein Gesicht.",
        stage6: "Technische Systeme", stage6Desc: "Installation von Elektrik, Heizung, Sanitär und Lüftung — alle Leitungen werden fachgerecht verlegt.",
        stage7: "Innenausbau", stage7Desc: "Wände, Böden, Türen und die komplette Ausstattung bis zum schlüsselfertigen Innenausbau.",
        stage8: "Prüfung & Inspektion", stage8Desc: "Abnahme aller Systeme und Qualitätskontrolle, damit alles einwandfrei funktioniert.",
        stage9: "Übergabe & Einzug", stage9Desc: "Schlüsselübergabe inklusive aller Dokumente — Ihr neues Zuhause ist bezugsfertig.",
        ctaStagesTitle: "Bereit zu bauen?", ctaStagesDesc: "Kontaktieren Sie uns",
        ctaContact: "Beratung erhalten", ctaProjects: "Projekte ansehen",
        ctaProjectsTitle: "Möchten Sie ein ähnliches Haus?", ctaProjectsDesc: "Wir besprechen Ihr Projekt",
        advantagesTitle: "Unsere Vorteile", advantagesDesc: "Warum Kunden Eco Haus Meister wählen",
        advIntro: "Eco Meister Haus baut energieeffiziente Häuser nach europäischen Standards.",
        adv1: "Kompletter Bauzyklus", adv1Desc: "Von der Planung bis zur Übergabe",
        adv2: "Schnelle Bauzeit", adv2Desc: "Moderne Technologien verkürzen die Bauzeit",
        adv3: "Umweltfreundliche Materialien", adv3Desc: "Sichere und energieeffiziente Lösungen",
        adv4: "Optimale Kosten", adv4Desc: "Bestes Preis-Leistungs-Verhältnis",
        adv5: "Moderne Technologien", adv5Desc: "SIP und innovative Lösungen",
        adv6: "Individuelle Herangehensweise", adv6Desc: "Wir berücksichtigen alle Kundenwünsche",
        adv7: "Energieeffizienz", adv7Desc: "Klasse A+ — Heizkosten um bis zu 60% reduziert",
        adv8: "Europäische Standards", adv8Desc: "Wir bauen nach europäischen Normen",
        advFaqTitle: "Häufig gestellte Fragen",
        advFaq1Q: "Wie langlebig ist ein SIP-Haus?", advFaq1A: "SIP-Paneele halten Belastungen wie Ziegelwände stand.",
        advFaq2Q: "Wie energieeffizient ist ein SIP-Haus im Winter?", advFaq2A: "Klasse A+ verbraucht 50–60% weniger Heizenergie.",
        advFaq3Q: "Entspricht die Konstruktion europäischen Standards?", advFaq3A: "Ja. Alle Paneele durchlaufen Qualitätskontrolle.",
        advCtaTitle: "Überzeugt von unseren Vorteilen?", advCtaDesc: "Kontaktieren Sie uns",
        projectsTitle: "Unsere Projekte", projectsDesc: "Entdecken Sie unsere realisierten Bauprojekte.",
        catModern: "Modern", catCountry: "Landhaus", catMinimal: "Minimalistisch",
        catModernTitle: "Moderne Häuser", catCountryTitle: "Landhäuser", catMinimalTitle: "Minimalistische Häuser",
        project1: "Modernes Haus", project1Desc: "Energieeffizientes Haus mit modernem Design.",
        project1Full: "Vollständig energieeffizientes Haus mit SIP-Paneelen.",
        project2: "Landhaus", project2Desc: "Gemütliches Haus für eine Familie außerhalb der Stadt.",
        project2Full: "Geräumiges Haus mit Terrasse und Panoramafenstern.",
        project3: "Minimalistisches Haus", project3Desc: "Stilvolles Haus im modernen minimalistischen Design.",
        project3Full: "Moderner Minimalismus mit funktionalem Grundriss.",
        viewProject: "Ansehen",
        heroTitle1: "Schneller, einfacher und effizienter bauen",
        heroTitle2: "Moderne SIP-Technologien",
        heroTitle3: "Zuverlässige und energieeffiziente Häuser",
        whyTitle: "Warum Eco Haus Meister", whyDesc: "Vier Gründe, warum uns Menschen den Bau anvertrauen",
        why1Title: "Schnell", why1Desc: "Schlüsselfertiges Haus in 3–6 Monaten",
        why2Title: "Umweltfreundlich", why2Desc: "Nur zertifizierte Materialien ohne Schadstoffe",
        why3Title: "Europäische Standards", why3Desc: "Wir bauen nach europäischen Energieeffizienznormen",
        why4Title: "Individuell", why4Desc: "Jedes Projekt für den spezifischen Kunden",
        sipBadge: "Technologie der Zukunft", sipTitle: "SIP Premium Class — Häuser der nächsten Generation",
        sipDesc: "SIP-Paneele — zwei OSB-Platten mit Polystyrolschaum. Im Winter warm, im Sommer kühl, schneller als Ziegelhaus.",
        sipPoint1: "Energieeffizienzklasse A+ — Heizkosten bis zu 60% reduziert",
        sipPoint2: "Hausmontage — 2 bis 4 Wochen",
        sipPoint3: "Lebensdauer — über 50 Jahre",
        sipPoint4: "Nach europäischen Standards zertifiziert",
        sipCta: "Mehr über Bauphasen erfahren",
        sipStat1: "Heizkosteneinsparung", sipStat2: "schneller als Ziegelhäuser",
        sipStat3: "Jahre Lebensdauer", sipStat4: "Energieeffizienzklasse",
        materialsTitle: "Materialien und Technologien", materialsDesc: "Wir verwenden nur europäisch bewährte Materialien",
        mat1Title: "OSB + Polystyrolschaum", mat1Desc: "Hochwertiger Polystyrolschaum zwischen zwei OSB-Platten.",
        mat2Title: "Lüftung und Klima", mat2Desc: "Wärmerückgewinnung und moderne Klimasteuerungssysteme.",
        mat3Title: "Fassade und Dach", mat3Desc: "Langlebige Fassadensysteme von europäischen Herstellern.",
        stagesPreviewTitle: "Wie wir bauen", stagesPreviewDesc: "Vom ersten Anruf bis zur Schlüsselübergabe",
        stagesPrev1: "Grundstück und Fundament", stagesPrev2: "Planung und Paneele",
        stagesPrev3: "Montage und Dach", stagesPrev4: "Ausbau und Einzug",
        stagesPreviewCta: "Alle Phasen im Detail →",
        projectsPreviewTitle: "Unsere Projekte", projectsPreviewDesc: "Fertiggestellte Häuser — von kompakt bis geräumig",
        projectsPreviewCta: "Alle Projekte ansehen →",
        designBadge: "Nur für Sie", designTitle: "Individuelles Design für Ihren Lebensstil",
        designDesc: "Jedes Haus wird individuell entworfen — Grundstück, Familie, Gewohnheiten und Budget.",
        designPoint1: "Freier Grundriss", designPoint2: "Wahl von Fassade und Dach",
        designPoint3: "Jeder Einrichtungsstil", designPoint4: "An Ihr Grundstück angepasst",
        designCta: "Projekt besprechen", ctaBadge: "Starten Sie heute",
        ctaMainTitle: "Bereit, Ihr Traumhaus zu bauen?",
        ctaMainDesc: "Erzählen Sie uns von Ihrem Projekt — wir berechnen die Kosten. Kostenlos und unverbindlich.",
        ctaMainBtn1: "Beratung erhalten", ctaMainBtn2: "Projekte ansehen",
        aboutTitle: "Über unser Unternehmen", aboutDesc: "Wir spezialisieren uns auf SIP-Häuser und individuellen Hausbau nach Maß.",
        about: "Über uns", aboutHeroTitle: "Über uns",
        aboutHeroDesc: "Wir bauen moderne, zuverlässige und energieeffiziente Häuser nach europäischen Standards",
        aboutCompanyTitle: "Wer wir sind",
        aboutCompanyText1: "Eco Meister Haus ist ein Team von Bau-Fachleuten. Wir bauen energieeffiziente SIP-Häuser und individuelle Projekte nach Maß — alles nach europäischen Standards.",
        aboutCompanyText2: "Unser Ziel: Häuser, die angenehm zu leben und kostengünstig zu unterhalten sind.",
        aboutValuesTitle: "Unsere Grundsätze", aboutValuesDesc: "Qualität, Ökologie und europäische Standards",
        val1Title: "Umweltfreundlich", val1Desc: "Nur sichere, zertifizierte Materialien",
        val2Title: "Qualität", val2Desc: "Jede Phase durchläuft Qualitätskontrolle",
        val3Title: "Europäische Standards", val3Desc: "Wir bauen gemäß europäischen Vorschriften",
        aboutApproachTitle: "Unsere Herangehensweise", aboutApproachDesc: "Wie wir mit jedem Kunden arbeiten",
        approach1Title: "Wir hören zu", approach1Desc: "Ausführliches Gespräch über Ihre Wünsche.",
        approach2Title: "Wir planen für Sie", approach2Desc: "Individuelles Projekt für Ihr Grundstück.",
        approach3Title: "Wir bauen transparent", approach3Desc: "Fester Kostenvoranschlag ohne versteckte Kosten.",
        approach4Title: "Wir liefern schlüsselfertig", approach4Desc: "Vollständige Unterlagen und Garantie.",
        aboutTechTitle: "Technologien und Materialien",
        aboutTechText1: "SIP-Technologie — Sandwichplatten aus OSB und Polystyrolschaum.",
        aboutTechText2: "SIP-Haus schneller als Ziegelhaus. Heizkosten sinken um bis zu 60%.",
        techStat1: "Heizkosteneinsparung", techStat2: "schneller als Ziegelhäuser",
        techStat3: "Jahre Lebensdauer", techStat4: "Energieeffizienzklasse",
        aboutCtaTitle: "Bereit, Ihr Traumhaus zu bauen?", aboutCtaDesc: "Wir finden die optimale Lösung",
        bank: "BANKDATEN", social: "SOZIALE MEDIEN",
        srvSectionTitle: "Was wir anbieten",
        srvSectionDesc: "Alle Leistungen aus einer Hand — kein Koordinationsaufwand für Sie",
        srv1Title: "SIP-Montage & Rohbau",
        srv1Desc: "Lieferung und Montage des SIP-Kits inkl. Dachstruktur. Hausbox in 2–4 Wochen bezugsfertig.",
        srv2Title: "Fundament & Erdarbeiten",
        srv2Desc: "Betonfundament nach statischen Plänen, Erdarbeiten, Drainage und Bodenplatte.",
        srv3Title: "Dach, Fenster & Türen",
        srv3Desc: "Metalldach, PVC-Fenster (Uw ≤ 0,80), Außen- und Innentüren — komplett montiert.",
        srv4Title: "WDVS Fassade & Putz",
        srv4Desc: "Außen-Wärmedämmverbundsystem mit Basaltwolle 100 mm + Armierungsputz + Silikatputz. Energieklasse A+.",
        srv5Title: "Haustechnik (TGA)",
        srv5Desc: "Heizung, Sanitär und Elektrik — vollständiger Ausbau nach deutschen Normen.",
        srv6Title: "Innenausbau & Finishing",
        srv6Desc: "Böden, Wände, Decken, Sanitärkeramik — schlüsselfertiger Innenausbau nach Ihren Wünschen.",
        srv7Title: "Planung & Baugenehmigung",
        srv7Desc: "Architekturplanung, Statik, Energieausweis und Baugenehmigung nach deutschem Baurecht.",
        srv8Title: "Alles aus einer Hand — schlüsselfertig",
        srv8Desc: "Kein Koordinationsaufwand, kein Risiko. Wir übernehmen jeden Schritt und übergeben Ihnen ein bezugsfertiges Haus mit Garantie.",
        srvCalcTitle: "Beispielkalkulation: SIP-Haus 174 m²",
        srvCalcDesc: "Ein reales Projekt — aufgeschlüsselt nach Gewerk. Ihr Preis hängt von Grundstück, Ausstattung und Region ab.",
        kfwTitle: "Bis zu 150.000 € Förderung für Ihr SIP-Haus",
        kfwDesc: "Unsere Häuser erfüllen die Anforderungen für KfW-Förderprogramme. Wir begleiten Sie beim Antrag.",
        kfwProcess: "Wie wir vorgehen",
        srvFaqTitle: "Was unsere Kunden fragen",
        srvCtaTitle: "Bereit, Ihr Haus zu planen?",
        srvCtaDesc: "Erzählen Sie uns von Ihrem Grundstück und Ihren Wünschen — wir erstellen innerhalb von 48 Stunden ein kostenloses Angebot.",
        srvCtaBtn: "Jetzt kostenlos anfragen",
        srvFaq1Q: "Was kostet ein SIP-Haus schlüsselfertig?",
        srvFaq1A: "Ab ca. 260 €/m² für den SIP-Kit allein, oder 700–900 €/m² für ein vollständig schlüsselfertiges Haus inkl. Fundament, TGA und Innenausbau. Unser Beispielprojekt (174 m², Berlin) liegt bei ca. 151.667 € vor KfW-Abzug.",
        srvFaq2Q: "Wie lange dauert der Bau?",
        srvFaq2A: "Die SIP-Hausbox (Rohbau) wird in 2–4 Wochen montiert. Der gesamte Prozess vom ersten Spatenstich bis zur Schlüsselübergabe dauert in der Regel 3–6 Monate.",
        srvFaq3Q: "Kann ich KfW-Förderung bekommen?",
        srvFaq3A: "Ja. SIP-Häuser können die Energieeffizienzklasse 40 oder 55 erreichen und damit für KfW 297/298 qualifizieren — zinsgünstiges Darlehen bis 150.000 €. Der Antrag muss vor Baubeginn gestellt werden.",
        srvFaq4Q: "Bauen Sie nur in Berlin?",
        srvFaq4A: "Unser Schwerpunkt liegt in Berlin und der Region Brandenburg. Projekte in anderen Bundesländern besprechen wir gerne im Einzelfall — sprechen Sie uns an.",
        srvFaq5Q: "Wie energieeffizient sind SIP-Häuser?",
        srvFaq5A: "SIP-Häuser erreichen regelmäßig Energieeffizienzklasse A+. Die Heizkosten liegen um bis zu 60 % niedriger als bei einem konventionellen Massivbau. In Kombination mit Wärmepumpe nähert sich das Gebäude dem Passivhausstandard.",
        srvFaq6Q: "Bieten Sie auch einzelne Gewerke an?",
        srvFaq6A: "Ja, wir können auch einzelne Leistungen übernehmen — z. B. nur SIP-Montage, nur Dach oder nur Fassade. Das Rundum-Paket ist jedoch wirtschaftlich am vorteilhaftesten.",
        srvCtaLang: "Wir sprechen Deutsch, Englisch, Russisch &amp; Rumänisch",
    }
};
 
function toggleLang() {
    document.getElementById("langMenu").classList.toggle("hidden");
}
 
function toggleLangMobile() {
    const m = document.getElementById("langMenuMobile");
    if (m) m.classList.toggle("hidden");
}
 
function setLangBoth(lang) {
    setLang(lang);
    const m = document.getElementById("langMenuMobile");
    if (m) m.classList.add("hidden");
    const shortNames = { ru: "RU", ro: "RO", en: "EN", de: "DE" };
    const mob = document.getElementById("currentLangMobile");
    if (mob) mob.innerText = shortNames[lang] || lang.toUpperCase();
}
 
function setLang(lang) {
    const shortNames = { ru: "RU", ro: "RO", en: "EN", de: "DE" };
    const el = document.getElementById("currentLang");
    if (el) el.innerText = translations[lang].lang;
    const mob = document.getElementById("currentLangMobile");
    if (mob) mob.innerText = shortNames[lang] || lang.toUpperCase();
    const elements = document.querySelectorAll("[data-key]");
    elements.forEach(el => {
        const key = el.getAttribute("data-key");
        if (translations[lang][key]) {
            if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") {
                el.placeholder = translations[lang][key];
            } else {
                el.innerText = translations[lang][key];
            }
        }
    });
    document.getElementById("langMenu").classList.add("hidden");
    const lm = document.getElementById("langMenuMobile");
    if (lm) lm.classList.add("hidden");
    localStorage.setItem("lang", lang);
    localStorage.setItem("userChoseLang", "true");
}
 
function toggleMenu() {
    const menu = document.getElementById("mobileMenu");
    const b1 = document.getElementById("burger1");
    const b2 = document.getElementById("burger2");
    const b3 = document.getElementById("burger3");
    const isOpen = menu.dataset.open === "true";
    if (!isOpen) {
        menu.classList.remove("hidden");
        menu.style.maxHeight = "0px";
        menu.style.opacity = "0";
        menu.style.overflow = "hidden";
        menu.style.transition = "max-height 0.35s ease, opacity 0.25s ease";
        requestAnimationFrame(() => { requestAnimationFrame(() => {
            menu.style.maxHeight = menu.scrollHeight + "px";
            menu.style.opacity = "1";
        }); });
        menu.dataset.open = "true";
        if (b1) b1.style.transform = "translateY(8px) rotate(45deg)";
        if (b2) b2.style.opacity = "0";
        if (b3) b3.style.transform = "translateY(-8px) rotate(-45deg)";
    } else {
        menu.style.maxHeight = "0px";
        menu.style.opacity = "0";
        menu.dataset.open = "false";
        if (b1) b1.style.transform = "";
        if (b2) b2.style.opacity = "";
        if (b3) b3.style.transform = "";
        setTimeout(() => {
            menu.classList.add("hidden");
            menu.style.maxHeight = "";
            menu.style.opacity = "";
            menu.style.transition = "";
        }, 350);
    }
}
 
function openModal(id) {
    document.getElementById(id).classList.remove("hidden");
    document.getElementById(id).classList.add("flex");
}
 
function closeModal(id) {
    document.getElementById(id).classList.add("hidden");
    document.getElementById(id).classList.remove("flex");
}
 
function toggleFaq(btn) {
    const answer = btn.nextElementSibling;
    const icon = btn.querySelector(".faq-icon");
    const isOpen = !answer.classList.contains("hidden");
    answer.classList.toggle("hidden");
    if (icon) icon.textContent = isOpen ? "+" : "−";
}
 
document.addEventListener("DOMContentLoaded", () => {
    if (!localStorage.getItem("userChoseLang")) {
        localStorage.setItem("lang", "de");
    }
    const savedLang = localStorage.getItem("lang") || "de";
    setLang(savedLang);
    document.documentElement.style.visibility = '';
 
    document.addEventListener("click", (e) => {
        const langMenu = document.getElementById("langMenu");
        const langMenuMobile = document.getElementById("langMenuMobile");
        if (langMenu && !e.target.closest("[onclick='toggleLang()']") && !e.target.closest("#langMenu")) {
            langMenu.classList.add("hidden");
        }
        if (langMenuMobile && !e.target.closest("[onclick='toggleLangMobile()']") && !e.target.closest("#langMenuMobile")) {
            langMenuMobile.classList.add("hidden");
        }
    });
 
    let currentSlide = 0;
    const slides = document.querySelectorAll(".slide");
    const dots = document.querySelectorAll(".dot");
    const prevBtn = document.getElementById("prevSlide");
    const nextBtn = document.getElementById("nextSlide");
 
    if (slides.length > 0 && prevBtn && nextBtn) {
        function showSlide(index) {
            slides.forEach((slide, i) => {
                slide.classList.add("hidden");
                if (dots[i]) { dots[i].classList.remove("bg-white"); dots[i].classList.add("bg-white/50"); }
            });
            slides[index].classList.remove("hidden");
            if (dots[index]) { dots[index].classList.add("bg-white"); dots[index].classList.remove("bg-white/50"); }
        }
        function nextSlide() { currentSlide = (currentSlide + 1) % slides.length; showSlide(currentSlide); }
        function prevSlide() { currentSlide = (currentSlide - 1 + slides.length) % slides.length; showSlide(currentSlide); }
        nextBtn.addEventListener("click", nextSlide);
        prevBtn.addEventListener("click", prevSlide);
        dots.forEach((dot, i) => { dot.addEventListener("click", () => { currentSlide = i; showSlide(i); }); });
        showSlide(0);
        setInterval(nextSlide, 5000);
    }
 
    document.querySelectorAll('.fixed.inset-0').forEach(modal => {
        modal.addEventListener('click', (e) => {
            if (e.target === modal) { modal.classList.add('hidden'); modal.classList.remove('flex'); }
        });
    });
});
 
const galleryState = {};
function galleryNext(id, total) {
    if (!galleryState[id]) galleryState[id] = 0;
    galleryState[id] = (galleryState[id] + 1) % total;
    updateGallery(id, total);
}
function galleryPrev(id, total) {
    if (!galleryState[id]) galleryState[id] = 0;
    galleryState[id] = (galleryState[id] - 1 + total) % total;
    updateGallery(id, total);
}
function updateGallery(id, total) {
    const track = document.getElementById(id);
    const idx = galleryState[id];
    track.style.transform = `translateX(-${idx * 100}%)`;
    const num = id.replace('gallery', '');
    const dotsEl = document.getElementById('dots' + num);
    if (dotsEl) {
        dotsEl.querySelectorAll('span').forEach((dot, i) => {
            dot.className = i === idx ? 'w-2 h-2 rounded-full bg-white block' : 'w-2 h-2 rounded-full bg-white/50 block';
        });
    }
}